// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "Table Pay": assets TestHelpers
//
// Command:
// $ goagen
// --design=github.com/zenreach/platypus/platform/tablepay/api/design
// --out=$(GOPATH)/src/github.com/zenreach/platypus/platform/tablepay/api
// --version=v1.3.1

package test
