// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "Table Pay": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/tablepay/api/design
// --out=$(GOPATH)/src/github.com/tablepay/api
// --version=v1.3.1

package app
